#  ln -s ~/Dropbox\ \(Personal\) ~/Dropbox
## delete existing file to Dropbox
#  rm -rf ~/.zshrc
## symlink file back to your local directory
#  ln -s ${HOME}/Dropbox/Apps/ohmyzsh/zshrc ${HOME}/.zshrc

# Path to your oh-my-zsh installation.
export DOTFILES=${HOME}/dotfiles
export ZSH=${HOME}/.oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="boom"

if [ -e /usr/share/terminfo/x/xterm-256color ]; then
    export TERM='xterm-256color'
else
    export TERM='xterm-color'
fi

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=${DOTFILES}/oh-my-zsh/custom

# Additional private configs
for config_file (${HOME}/Dropbox/syslocal/oh-my-zsh/*.zsh(N)); do
  source $config_file
done

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(zsh-syntax-highlighting)

# User configuration
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:$PATH"

# Composer
export PATH="$PATH:$HOME/.composer/vendor/bin"
export PATH="$PATH:./vendor/bin"

# Node
export PATH="$PATH:$HOME/.npm-packages/bin"
export PATH="$PATH:./node_modules/.bin"

# Homebrew casks
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

# set color scheme
export CLICOLOR=1
export TERM=xterm-256color

# Android
export ANDROID_HOME=${HOME}/Library/Android/sdk
export PATH=${PATH}:${ANDROID_HOME}/tools
export PATH=${PATH}:${ANDROID_HOME}/platform-tools

source $ZSH/oh-my-zsh.sh

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

export NVM_DIR="/Users/neil/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
eval $(/usr/libexec/path_helper -s)

export PATH="$HOME/.yarn/bin:$PATH"
