#  ln -s ~/Dropbox\ \(Personal\) ~/Dropbox
## delete existing file to Dropbox
#  rm -rf ~/.zshrc
## symlink file back to your local directory
#  ln -s ~/Dropbox/Apps/ohmyzsh/zshrc ~/.zshrc

# Path to your oh-my-zsh installation.
export ZSH=${HOME}/.oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="zero"

# Oh my zsh folder
OMZ_FOLDER=${HOME}/dotfiles/ohmyzsh

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=${OMZ_FOLDER}/custom

# Base16 Shell
BASE16_SHELL="$ZSH_CUSTOM/base16-shell/base16-material.dark.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(bower brew docker git laravel osx vagrant)

# User configuration
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:$PATH"
#export PATH="/usr/local/sbin:$PATH"

# Composer
export PATH="$PATH:$HOME/.composer/vendor/bin"

# VIM
export PATH="/opt/local/bin:$PATH"

source $ZSH/oh-my-zsh.sh

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"
